### ISSUE TITLE
[BUG] How to run?

### ISSUE THREAD

**Issue by urmamalikesme** [Anequit/SCD#20]
Any instructions how to RUN, please.

**Comment by Anequit** [comment]
What platform are you on?

**Comment by Anequit** [comment]
Head to the releases page and download win-x64.zip then extract it and run the exe file

**Comment by cacho-22** [comment]
Can you please say how to run on OS X?

**Comment by Anequit** [comment]
I'm not entirely sure on how to run it with OSX since I don't own a mac. I know it works due to someone helping me test it with their mac, but I don't remember how we got it to run.
