### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Thishastobespam** [Anequit/SCD#21]
**Describe the bug**
After extracting and running the .exe (with & without administrator). file it just perpetually stays at 0% and will not download the file.

**To Reproduce**
1. add cyberdrop link,
2. Select folder to download to
3. Wait.

**Expected behavior**
I was expecting the files from cyberdrop to be downloaded into the selected folder.

**Screenshots**
![image](https://user-images.githubusercontent.com/109786925/180382318-985c4967-ce07-4ff5-8631-02ec5fc85a25.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 2.1.0
![image_2022-07-22_170139972](https://user-images.githubusercontent.com/109786925/180382526-8d2b1643-a28b-463a-bf75-9e47aa4c3373.png)

**Comment by Anequit** [comment]
I have noticed this before with cyberdrop. Sometimes the website just refuses to send the file. In the past it was a matter of just waiting till it worked again, so for now that's all I can recommend doing.

**Comment by Thishastobespam** [comment]
Hey dude, that's odd.

Thanks for the reply, will update with any success.

Thanks,
