### ISSUE TITLE
Unable to delete folder after download

### ISSUE THREAD

**Issue by TonySphabmixay** [Anequit/SCD#25]
After assigning a download path in SCD, once complete and I've removed content from said folder, unable to delete that folder. Screenshot attached, folder name removed for privacy.
![SCD](https://user-images.githubusercontent.com/47992516/187057114-cbe69e9c-c083-40b8-b202-e3e8b871a77d.png)

**Comment by Anequit** [comment]
Either it hasn't completely finished or is stuck retrying a file, but if you close SCD it should allow you to delete the folder
